autoload, "tao-ncpa.i",
    tao_ncpa,
    tao_ncpa_center_wfs,
    tao_ncpa_cmd_and_capture,
    tao_ncpa_dmshape,
    tao_ncpa_get,
    tao_ncpa_init_exposure,
    tao_ncpa_load_ref,
    tao_ncpa_rm_focus,
    tao_ncpa_rm_tip,
    tao_ncpa_rm_tiptilt,
    tao_ncpa_rm_tilt,
    tao_ncpa_roi_to_center,
    tao_ncpa_roi_to_max,
    tao_ncpa_set;
