/*
 * yorz.i - generated by yorick-z configure script
 * autoloads for yorick-z package
 */

autoload, "zlib.i", z_deflate, z_inflate, z_flush, z_setdict, z_crc32;
autoload, "png.i", png2, png_read, png_write, png_scale, png_map, png_pcal;
autoload, "jpeg.i", jpeg2, jpeg_read, jpeg_write;
